"""a

Revision ID: 1e099f2cd410
Revises: 18d363fdc3c0
Create Date: 2023-07-12 15:08:34.078059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e099f2cd410'
down_revision = '18d363fdc3c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('finish_dtime', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'finish_dtime')
    # ### end Alembic commands ###
