"""a

Revision ID: 7b73fccf87c9
Revises: 8b2cbdacab54
Create Date: 2023-07-12 13:13:49.296239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b73fccf87c9'
down_revision = '8b2cbdacab54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('username', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('finish_dtime', sa.TIMESTAMP(), nullable=True))
    op.drop_column('tickets', 'reg_dtime')
    op.drop_column('users', 'reg_dtime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reg_dtime', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=False))
    op.add_column('tickets', sa.Column('reg_dtime', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=False))
    op.drop_column('tickets', 'finish_dtime')
    op.drop_column('tickets', 'username')
    # ### end Alembic commands ###
