"""a

Revision ID: a69f3a470cbf
Revises: 1e099f2cd410
Create Date: 2023-07-12 15:09:47.676431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a69f3a470cbf'
down_revision = '1e099f2cd410'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'reg_dtime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('reg_dtime', postgresql.TIMESTAMP(), server_default=sa.text("timezone('Asia/Irkutsk'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
