"""a

Revision ID: c825139c01b8
Revises: d88a57da755b
Create Date: 2023-07-12 16:54:39.102629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c825139c01b8'
down_revision = 'd88a57da755b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('total', sa.Float(), sa.Computed('quantity * price', ), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'total')
    # ### end Alembic commands ###
