"""a

Revision ID: d88a57da755b
Revises: a69f3a470cbf
Create Date: 2023-07-12 15:11:26.481597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88a57da755b'
down_revision = 'a69f3a470cbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('reg_dtime', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('Asia/Irkutsk', CURRENT_TIMESTAMP)"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'reg_dtime')
    # ### end Alembic commands ###
